---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kcdcluster
  region: us-east-1	
  version: "1.21"

kubernetesNetworkConfig:
  ipFamily: IPv6

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

iam:
  withOIDC: true

managedNodeGroups:
  - name: kcd-nodegroup
    instanceType: t3.medium
